name: RSpec Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and run containers
      run: docker-compose up -d

    - name: Wait for containers to start
      run: docker-compose ps && sleep 30

    - name: Run RSpec tests
      run: |
        docker-compose run app rake db:create
        docker-compose run app rake db:migrate
        docker-compose run --rm app bundle exec rspec
      env:
        RAILS_ENV: test

    - name: Stop and remove containers
      run: docker-compose down
