name: RSpec Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_USER: dev
          MYSQL_PASSWORD: expertiza
          MYSQL_ROOT_PASSWORD: expertiza
          MYSQL_DATABASE: reimplementation
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and run containers
      run: docker-compose up -d

    - name: Wait for containers to start
      run: docker-compose ps && sleep 30

    - name: Run RSpec tests
      run: docker-compose run --rm app bundle exec rspec

    - name: Stop and remove containers
      run: docker-compose down
